// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxdEq375MeehgKiX-yJzI0lS6P_MwiDeA',
    appId: '1:1057063102882:web:f8f558c267dcfebc46aafb',
    messagingSenderId: '1057063102882',
    projectId: 'final-project-be344',
    authDomain: 'final-project-be344.firebaseapp.com',
    storageBucket: 'final-project-be344.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9sDO8BiiY4fvfaeP_XwIU3vjeqzUnAII',
    appId: '1:1057063102882:android:a33c6dd9614d3a5646aafb',
    messagingSenderId: '1057063102882',
    projectId: 'final-project-be344',
    storageBucket: 'final-project-be344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLq4anCm3553vhR05r6_lYXuRp4GYFT_E',
    appId: '1:1057063102882:ios:2a227cf4a8b6847546aafb',
    messagingSenderId: '1057063102882',
    projectId: 'final-project-be344',
    storageBucket: 'final-project-be344.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLq4anCm3553vhR05r6_lYXuRp4GYFT_E',
    appId: '1:1057063102882:ios:a593aaae3c194e2246aafb',
    messagingSenderId: '1057063102882',
    projectId: 'final-project-be344',
    storageBucket: 'final-project-be344.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
